// ===================================================================
// Minuetto — database dei 600 argomenti
// 3 livelli × 8 categorie × 25 argomenti.
//  - facile:     curiosità e basi, bastano buone fonti divulgative
//  - intermedio: serve studiare sul serio (manuali, enciclopedie)
//  - esperto:    argomenti accademici da Google Scholar / JSTOR / RILM
// ===================================================================

const LEVELS = {
  facile:     { label: "Facile",     emoji: "🌱", color: "#8fae7e",
                desc: "Curiosità e basi della musica: bastano buone fonti divulgative." },
  intermedio: { label: "Intermedio", emoji: "🌿", color: "#c49a63",
                desc: "Si fa sul serio: servono manuali, enciclopedie e un po' di metodo." },
  esperto:    { label: "Esperto",    emoji: "🌳", color: "#b06565",
                desc: "Argomenti accademici tostissimi: Google Scholar, JSTOR e coraggio." },
};

const CATEGORIES = {
  teoria:      { label: "Teoria e analisi",              emoji: "📐", color: "#9a8fc4" },
  storia:      { label: "Storia della musica",           emoji: "🏛️", color: "#bf7d92" },
  composizione:{ label: "Armonia e composizione",        emoji: "✒️", color: "#7faca9" },
  generi:      { label: "Generi e popular music",        emoji: "🎸", color: "#c49a63" },
  etno:        { label: "Etnomusicologia",               emoji: "🌍", color: "#8fae7e" },
  acustica:    { label: "Acustica e psicoacustica",      emoji: "🔬", color: "#7f97bd" },
  organologia: { label: "Organologia e prassi esecutiva",emoji: "🎻", color: "#b08a5e" },
  musicologia: { label: "Notazione e musicologia",       emoji: "📜", color: "#a487bd" },
};

const TOPICS_ESPERTO = [
  // ------------------------- TEORIA E ANALISI (25) -------------------------
  { c: "teoria", t: "L'Ursatz nell'analisi schenkeriana: Urlinie, Bassbrechung e i livelli strutturali (foreground, middleground, background)" },
  { c: "teoria", t: "La teoria neo-riemanniana: le trasformazioni P, L, R e la navigazione del Tonnetz" },
  { c: "teoria", t: "La pitch-class set theory di Allen Forte: forma prima, vettore intervallare e relazioni Z" },
  { c: "teoria", t: "La Grundgestalt schoenberghiana e il principio della developing variation" },
  { c: "teoria", t: "La teoria delle funzioni armoniche di Hugo Riemann e il dualismo armonico: il problema del minore" },
  { c: "teoria", t: "Il partimento napoletano: apprendimento del contrappunto improvvisato nei conservatori del Settecento" },
  { c: "teoria", t: "La règle de l'octave: armonizzazione della scala nella prassi del basso continuo francese e italiano" },
  { c: "teoria", t: "Gli schemi galanti di Robert Gjerdingen: Prinner, Romanesca, Monte, Fonte e Ponte" },
  { c: "teoria", t: "La teoria delle funzioni formali di William Caplin: sentence, period e la tight-knit organization" },
  { c: "teoria", t: "La Sonata Theory di Hepokoski e Darcy: rotazioni, medial caesura e i cinque tipi di sonata" },
  { c: "teoria", t: "La modulazione enarmonica: la sesta tedesca riscritta come settima di dominante e i suoi usi da Schubert a Wolf" },
  { c: "teoria", t: "L'accordo di Tristano: un secolo e mezzo di analisi in conflitto (funzionale, appoggiatura, atonale, trasformazionale)" },
  { c: "teoria", t: "Tactus e proporzioni mensurali nella teoria rinascimentale: tempus, prolatio e i segni di proporzione" },
  { c: "teoria", t: "I modi ecclesiastici da Boezio al Dodecachordon di Glareano: autentici, plagali e i nuovi modi eolio e ionico" },
  { c: "teoria", t: "La solmisazione guidoniana: esacordi naturale, molle e duro, le mutazioni e il gamut medievale" },
  { c: "teoria", t: "Il concetto di consonanza da Pitagora a Zarlino: rapporti numerici, senario e la giustificazione della terza" },
  { c: "teoria", t: "Ipermetro e anacrusi strutturale: la teoria del fraseggio di William Rothstein" },
  { c: "teoria", t: "La Generative Theory of Tonal Music di Lerdahl e Jackendoff: riduzione time-span e riduzione prolongazionale" },
  { c: "teoria", t: "La teoria della proiezione metrica di Christopher Hasty: il metro come processo e non come griglia" },
  { c: "teoria", t: "La progressione omnibus e la condotta delle parti parsimoniosa nel cromatismo ottocentesco" },
  { c: "teoria", t: "Le clausole cantizans, tenorizans e basizans: la cadenza nella polifonia pre-tonale" },
  { c: "teoria", t: "La musica ficta: semitonia sotto-intesa, criteri editoriali e prassi esecutiva nella polifonia antica" },
  { c: "teoria", t: "La teoria del contorno melodico (contour theory) di Robert Morris e i c-segments" },
  { c: "teoria", t: "L'analisi paradigmatica di Nicolas Ruwet e la tripartizione semiotica di Jean-Jacques Nattiez" },
  { c: "teoria", t: "Tonicizzazione vs modulazione: dove finisce l'una e comincia l'altra secondo Schenker, Schoenberg e la teoria nordamericana" },

  // ------------------------ STORIA DELLA MUSICA (25) ------------------------
  { c: "storia", t: "L'Ars Nova francese: il Roman de Fauvel, Philippe de Vitry e la nuova notazione del Trecento" },
  { c: "storia", t: "L'Ars subtilior: la complessità ritmica estrema del Codex Chantilly e di Baude Cordier" },
  { c: "storia", t: "La scuola di Notre-Dame: organum duplum, clausulae sostitutive e i sei modi ritmici" },
  { c: "storia", t: "Il mottetto isoritmico da Machaut a Du Fay: talea, color e la panisoritmia" },
  { c: "storia", t: "La messa ciclica su cantus firmus: la tradizione dell'Homme armé da Du Fay a Palestrina" },
  { c: "storia", t: "Il madrigale italiano tardo: il cromatismo sperimentale di Gesualdo, Luzzaschi e l'arcicembalo di Vicentino" },
  { c: "storia", t: "La seconda pratica: la polemica Artusi-Monteverdi e la nascita della dissonanza espressiva" },
  { c: "storia", t: "La Camerata de' Bardi e la nascita dell'opera: recitar cantando, Peri, Caccini e il mito della tragedia greca" },
  { c: "storia", t: "La policoralità veneziana: i cori spezzati, i Gabrieli e l'acustica di San Marco" },
  { c: "storia", t: "La tragédie lyrique di Lully contro l'opera italiana: la Querelle des Bouffons del 1752" },
  { c: "storia", t: "Lo stile galante e l'Empfindsamkeit: la scuola napoletana e le fantasie di C.P.E. Bach" },
  { c: "storia", t: "La sinfonia pre-classica: la scuola di Mannheim, Sammartini e la questione delle origini della forma" },
  { c: "storia", t: "Il Beethoven tardo: le sonate op. 109-111 tra fuga, variazione e dissoluzione della forma sonata" },
  { c: "storia", t: "La Winterreise di Schubert come ciclo: coerenza tonale, Wanderer e la questione dell'unità" },
  { c: "storia", t: "La guerra dei romantici: Brahms e Hanslick contro la Neudeutsche Schule di Liszt e Wagner" },
  { c: "storia", t: "Il dramma musicale wagneriano: Leitmotiv, melodia infinita e la teoria del Gesamtkunstwerk" },
  { c: "storia", t: "Il Gruppo dei Cinque e il nazionalismo russo: orientalismo, modalità e il rifiuto del conservatorio" },
  { c: "storia", t: "La restaurazione del canto gregoriano a Solesmes: la querelle tra mensuralisti ed equalisti" },
  { c: "storia", t: "Il verismo musicale e la crisi della 'solita forma': drammaturgia e convenzioni nell'opera fin-de-siècle" },
  { c: "storia", t: "Jeux di Debussy: forma-momento, timbro e la modernità nascosta dell'ultimo Debussy" },
  { c: "storia", t: "La Seconda Scuola di Vienna: dall'atonalità libera di Erwartung al metodo dodecafonico del 1923" },
  { c: "storia", t: "Le Sacre du printemps: primitivismo, innovazione ritmica e la ricostruzione dello scandalo del 1913" },
  { c: "storia", t: "Il neoclassicismo tra le due guerre: Stravinskij, il rappel à l'ordre e la polemica con Schoenberg" },
  { c: "storia", t: "Šostakovič e il realismo socialista: il caso Lady Macbeth e l'articolo 'Caos invece di musica' del 1936" },
  { c: "storia", t: "I Ferienkurse di Darmstadt: serialismo integrale, alea e la frattura Cage-Boulez" },

  // --------------------- ARMONIA E COMPOSIZIONE (25) ---------------------
  { c: "composizione", t: "Le cinque specie di contrappunto nel Gradus ad Parnassum di Fux e la loro fortuna didattica" },
  { c: "composizione", t: "La fuga bachiana: soggetto, risposta reale e tonale, controsoggetto, stretto e i divertimenti" },
  { c: "composizione", t: "Il canone e le sue tipologie: per aumentazione, cancrizzante, a specchio ed enigmatico nell'Offerta Musicale" },
  { c: "composizione", t: "Il corale bachiano a quattro voci: condotta delle parti, note di passaggio e lo stile come corpus statistico" },
  { c: "composizione", t: "Il metodo dodecafonico: serie, matrice 12×12 e la combinatorialità esacordale di Milton Babbitt" },
  { c: "composizione", t: "La Klangfarbenmelodie: il terzo dei Cinque pezzi per orchestra op. 16 di Schoenberg e la melodia di timbri" },
  { c: "composizione", t: "Stockhausen e la Momentform: la tecnica dei gruppi da Gruppen a Momente" },
  { c: "composizione", t: "La musica spettrale: Partiels di Grisey, l'analisi dello spettro del trombone e la sintesi strumentale" },
  { c: "composizione", t: "La micropolifonia di Ligeti: Atmosphères, il canone sovrasaturo e la percezione della massa sonora" },
  { c: "composizione", t: "L'aleatorietà controllata di Lutosławski: le sezioni ad libitum dai Jeux vénitiens in poi" },
  { c: "composizione", t: "Citazione e collage: il terzo movimento della Sinfonia di Berio come commento a Mahler" },
  { c: "composizione", t: "La musica stocastica di Xenakis: Metastaseis, i glissandi di massa e il padiglione Philips" },
  { c: "composizione", t: "Il phasing di Steve Reich: da It's Gonna Rain a Piano Phase, processo graduale e pattern risultanti" },
  { c: "composizione", t: "La musique concrète di Pierre Schaeffer: objet sonore, ascolto ridotto e il solfège des objets" },
  { c: "composizione", t: "Lo studio di Colonia e la elektronische Musik: la sintesi additiva pura in Studie II di Stockhausen" },
  { c: "composizione", t: "L'accordo mistico di Skrjabin: armonia quartale, sintesi delle arti e il progetto Mysterium" },
  { c: "composizione", t: "Bartók e il sistema assiale di Ernő Lendvai: sezione aurea e Fibonacci — teoria o sovrainterpretazione?" },
  { c: "composizione", t: "Il linguaggio di Messiaen: modi a trasposizione limitata, ritmi non retrogradabili e accordi con risonanza" },
  { c: "composizione", t: "L'orchestrazione come disciplina: i trattati di Berlioz e Rimskij-Korsakov a confronto" },
  { c: "composizione", t: "Il tintinnabuli di Arvo Pärt: voce melodica e voce tintinnabulare, regole e ambiguità analitiche" },
  { c: "composizione", t: "Harry Partch e la just intonation estesa: la scala a 43 gradi e gli strumenti costruiti su misura" },
  { c: "composizione", t: "La microtonalità sistematica: i quarti di tono di Hába e l'ultracromatismo di Wyschnegradsky" },
  { c: "composizione", t: "La New Complexity: la notazione iper-dettagliata di Ferneyhough e il problema dell'ineseguibilità" },
  { c: "composizione", t: "La composizione algoritmica: dalla Illiac Suite di Hiller alla composizione assistita con OpenMusic" },
  { c: "composizione", t: "Il serialismo integrale: Structures Ia di Boulez, Mode de valeurs di Messiaen e l'organizzazione totale dei parametri" },

  // --------------------- GENERI E POPULAR MUSIC (25) ---------------------
  { c: "generi", t: "Il Delta blues: blue notes, forma AAB e il dibattito accademico sull'esistenza della 'scala blues'" },
  { c: "generi", t: "L'armonia del bebop: sostituzione di tritono, upper structures e il vocabolario di Parker e Powell" },
  { c: "generi", t: "Il modal jazz: Kind of Blue, i modi come campi armonici e l'abbandono della progressione funzionale" },
  { c: "generi", t: "Il free jazz e l'armolodia di Ornette Coleman: cosa significa davvero suonare 'senza accordi'" },
  { c: "generi", t: "La bossa nova: la batida di João Gilberto, la sincope brasiliana e il debito col samba de morro" },
  { c: "generi", t: "Il flamenco: i palos, il compás dodecuplo di soleá e bulería e la cadenza andalusa" },
  { c: "generi", t: "Il tango: dalla guardia vieja al nuevo tango di Piazzolla, tra habanera, milonga e fuga" },
  { c: "generi", t: "Il funk e 'The One': la concezione ritmica di James Brown e l'analisi del groove" },
  { c: "generi", t: "Le origini dell'hip-hop: il merry-go-round di Kool Herc, il breakbeat e la nascita del DJing" },
  { c: "generi", t: "Il sampling: l'Amen break, la sua diffusione e la giurisprudenza sul campionamento musicale" },
  { c: "generi", t: "Techno di Detroit e house di Chicago: genealogie, TR-808, TB-303 e il ruolo delle macchine 'fallite'" },
  { c: "generi", t: "Il dub giamaicano: King Tubby, lo studio di registrazione come strumento e la versione come pratica" },
  { c: "generi", t: "Il progressive rock: forme estese, metri irregolari e le appropriazioni della musica colta" },
  { c: "generi", t: "Il son cubano e la clave: struttura a due battute, direzionalità 3-2/2-3 e la derivazione della salsa" },
  { c: "generi", t: "Il fado: saudade, la guitarra portuguesa e la canonizzazione di Amália Rodrigues" },
  { c: "generi", t: "Dal gospel al soul: melisma, call and response e la secolarizzazione del sacro in Ray Charles e Aretha Franklin" },
  { c: "generi", t: "La scuola genovese dei cantautori: metrica, prosodia e il problema di cantare in italiano" },
  { c: "generi", t: "L'ambient di Brian Eno: Music for Airports, la musica generativa e l'ascolto ambientale" },
  { c: "generi", t: "Il krautrock e il motorik: Neu!, Can e la ritmica meccanica come estetica" },
  { c: "generi", t: "La disco: il four-on-the-floor, Giorgio Moroder e la produzione in studio come composizione" },
  { c: "generi", t: "Il punk e la sottocultura: l'analisi di Dick Hebdige e la retorica dell'autenticità DIY" },
  { c: "generi", t: "Il metal estremo: tecniche vocali gutturali, blast beat e la nascita dei metal studies accademici" },
  { c: "generi", t: "La musica per videogiochi: il chiptune, i vincoli tecnici del NES e la composizione adattiva" },
  { c: "generi", t: "Il bluegrass: lo stile Scruggs al banjo, l'high lonesome sound e la costruzione della tradizione" },
  { c: "generi", t: "Lo swing e le big band: section writing, arrangiamento e la composizione basata sul riff" },

  // -------------------------- ETNOMUSICOLOGIA (25) --------------------------
  { c: "etno", t: "Il gamelan giavanese: accordature slendro e pelog, irama e la struttura colotomica" },
  { c: "etno", t: "Il raga hindustani: that, rasa, gharana e l'architettura dell'alap" },
  { c: "etno", t: "Il tala: cicli ritmici hindustani e carnatici, il tihai e il solfeggio ritmico konnakol" },
  { c: "etno", t: "Il maqam arabo: gli ajnas, i quarti di tono e le convenzioni della modulazione modale" },
  { c: "etno", t: "Il radif persiano: dastgah, gushe e la trasmissione orale del repertorio classico iraniano" },
  { c: "etno", t: "Il canto difonico tuvano: khöömei, sygyt e kargyraa — produzione vocale e analisi spettrale" },
  { c: "etno", t: "La polifonia georgiana: il krimanchuli, le triadi non temperate e i sistemi di accordatura regionali" },
  { c: "etno", t: "Il canto a tenore sardo: la quintina, le formanti e il timbro gutturale di bassu e contra" },
  { c: "etno", t: "Le polifonie dei pigmei Aka: yodel, hoquetus e le registrazioni multitraccia di Simha Arom" },
  { c: "etno", t: "La mbira dzavadzimu degli Shona: cicli armonici, pattern interlocking e la cerimonia bira" },
  { c: "etno", t: "I tamburi parlanti dell'Africa occidentale: surrogati linguistici e la codifica dei toni" },
  { c: "etno", t: "Il gagaku giapponese: togaku e komagaku, lo sho e la questione del 'rallentamento' storico" },
  { c: "etno", t: "Il pansori coreano: timbro, tecnica vocale e i cinque racconti sopravvissuti del repertorio" },
  { c: "etno", t: "Il qawwali sufi: struttura, intensificazione estatica e la mediazione discografica di Nusrat Fateh Ali Khan" },
  { c: "etno", t: "La musica gnawa del Marocco: pentatonismo, guembri e i rituali di trance lila" },
  { c: "etno", t: "Lo joik sami: struttura circolare, referenzialità e la rivitalizzazione identitaria" },
  { c: "etno", t: "Il klezmer: i modi freygish e mi sheberakh, gli ornamenti krekhts e il revival americano" },
  { c: "etno", t: "Il canto bizantino: gli otto echoi, l'ison e la notazione neumatica della Nuova Metodo" },
  { c: "etno", t: "Lo shakuhachi e l'honkyoku: notazione katakana, il ma e l'estetica del suono singolo" },
  { c: "etno", t: "La bi-musicality di Mantle Hood: imparare a suonare come metodo di ricerca etnomusicologica" },
  { c: "etno", t: "La trascrizione in etnomusicologia: la dicotomia emic/etic e il melografo di Charles Seeger" },
  { c: "etno", t: "La scuola comparata di Berlino: Stumpf, Hornbostel e il Phonogramm-Archiv" },
  { c: "etno", t: "L'afrobeat di Fela Kuti: poliritmia, forme estese e la musica come pratica politica" },
  { c: "etno", t: "La cumbia: dalle origini afro-colombiane alle riappropriazioni transnazionali (chicha, sonidera, digitale)" },
  { c: "etno", t: "Le launeddas sarde: respirazione circolare, polifonia a bordone e le registrazioni di Bentzon" },

  // --------------------- ACUSTICA E PSICOACUSTICA (25) ---------------------
  { c: "acustica", t: "La serie armonica e il timbro: l'analisi di Fourier applicata ai suoni musicali" },
  { c: "acustica", t: "Temperamento equabile vs intonazione naturale: comma sintonico, comma pitagorico e i loro compromessi" },
  { c: "acustica", t: "Il temperamento mesotonico a quarto di comma: terze pure, quinta del lupo e i tasti spezzati" },
  { c: "acustica", t: "I temperamenti irregolari (Werckmeister, Kirnberger, Vallotti) e il dibattito sul 'buon temperamento' di Bach" },
  { c: "acustica", t: "La teoria della ruvidezza di Helmholtz: i battimenti come base fisica della dissonanza" },
  { c: "acustica", t: "Bande critiche e membrana basilare: la curva di Plomp e Levelt e la consonanza sensoriale" },
  { c: "acustica", t: "La fondamentale mancante: pitch virtuale e i modelli di percezione dell'altezza" },
  { c: "acustica", t: "Le curve isofoniche di Fletcher e Munson: loudness, phon e le conseguenze per il mixaggio" },
  { c: "acustica", t: "L'acustica delle sale da concerto: la formula di Sabine, il tempo di riverberazione e i parametri C80 e ITDG" },
  { c: "acustica", t: "La formante del cantante lirico: come una voce buca l'orchestra, spettro e vibrato" },
  { c: "acustica", t: "L'acustica delle canne d'organo: canne labiali e ad ancia, scaling e composizione dei registri" },
  { c: "acustica", t: "Gli archi e il moto di Helmholtz: stick-slip, pressione dell'arco e il punto di contatto" },
  { c: "acustica", t: "L'inarmonicità delle corde di pianoforte e lo stretching della curva di accordatura (curva di Railsback)" },
  { c: "acustica", t: "I modi di vibrazione delle membrane: perché il timpano ha un'altezza definita e il rullante no" },
  { c: "acustica", t: "Le figure di Chladni e i modi di vibrazione delle tavole armoniche del violino" },
  { c: "acustica", t: "L'effetto precedenza (Haas) e la localizzazione del suono: ITD, ILD e l'ascolto binaurale" },
  { c: "acustica", t: "L'orecchio assoluto: basi genetiche, periodo critico e la prevalenza nei parlanti di lingue tonali" },
  { c: "acustica", t: "La scala di Shepard e il glissando di Risset: i paradossi della percezione circolare dell'altezza" },
  { c: "acustica", t: "Il tritone paradox di Diana Deutsch e l'influenza della lingua madre sulla percezione" },
  { c: "acustica", t: "La sincronizzazione sensomotoria: beat induction, tapping e le basi neurali dell'entrainment ritmico" },
  { c: "acustica", t: "L'amusia congenita: cosa rivela sulla architettura cognitiva della percezione melodica" },
  { c: "acustica", t: "L'aspettativa musicale: la teoria ITPRA di David Huron e i modelli predittivi tipo IDyOM" },
  { c: "acustica", t: "Il frisson musicale: brividi, dopamina e i correlati fisiologici del piacere musicale" },
  { c: "acustica", t: "I profili tonali di Krumhansl e Kessler: la gerarchia tonale misurata empiricamente" },
  { c: "acustica", t: "La storia del diapason: dal La barocco al 440 Hz, le guerre del pitch e la normazione internazionale" },

  // ---------------- ORGANOLOGIA E PRASSI ESECUTIVA (25) ----------------
  { c: "organologia", t: "La classificazione Hornbostel-Sachs: logica, revisioni e i suoi limiti epistemologici" },
  { c: "organologia", t: "La liuteria cremonese: vernici, bombature e cosa dicono davvero dendrocronologia e analisi CT degli Stradivari" },
  { c: "organologia", t: "Clavicembalo e fortepiano: meccanica a salterello contro meccanica a martelletti, e le conseguenze sul repertorio" },
  { c: "organologia", t: "La viola da gamba: costruzione, accordatura per quarte e terza, e le ragioni del suo declino" },
  { c: "organologia", t: "Violino barocco e violino moderno: montatura, corde di budello, arco convesso e la trasformazione ottocentesca" },
  { c: "organologia", t: "Il corno naturale e la tecnica dei suoni chiusi: come si suonava cromatico senza pistoni" },
  { c: "organologia", t: "La tromba naturale e il registro clarino: la virtuosità barocca perduta e la sua riscoperta" },
  { c: "organologia", t: "Theobald Böhm e il flauto moderno: acustica, fori e la meccanica ad anelli" },
  { c: "organologia", t: "L'invenzione dei pistoni negli ottoni: cronologia, brevetti e le conseguenze sull'orchestrazione romantica" },
  { c: "organologia", t: "Serpentone, oficleide e la nascita della tuba: la voce grave degli ottoni prima e dopo il 1835" },
  { c: "organologia", t: "L'organo barocco nordtedesco: Arp Schnitger, il Werkprinzip e il repertorio di Buxtehude" },
  { c: "organologia", t: "Theremin e onde Martenot: i primi strumenti elettronici e il loro ingresso in orchestra" },
  { c: "organologia", t: "Il sintetizzatore modulare: Moog contro Buchla, east coast e west coast synthesis" },
  { c: "organologia", t: "Il pianoforte preparato di John Cage: tassonomia delle preparazioni e problemi di notazione" },
  { c: "organologia", t: "Il movimento della prassi storicamente informata: da Dolmetsch a Harnoncourt, strumenti originali e filologia del suono" },
  { c: "organologia", t: "L'ornamentazione barocca: trilli, appoggiature e le tavole di Bach, Couperin e Quantz a confronto" },
  { c: "organologia", t: "La cadenza nel concerto classico: improvvisazione, scrittura e le testimonianze su Mozart e Beethoven" },
  { c: "organologia", t: "Il diapason storico: variazioni regionali tra Sei e Ottocento e le conseguenze per l'esecuzione odierna" },
  { c: "organologia", t: "Le notes inégales: la convenzione francese dell'ineguaglianza e i suoi confini geografici" },
  { c: "organologia", t: "La realizzazione del basso continuo: trattatistica, stili nazionali e il ruolo del cembalista" },
  { c: "organologia", t: "Il castrato: fisiologia, repertorio, Farinelli e l'unica voce registrata (Alessandro Moreschi)" },
  { c: "organologia", t: "Il belcanto e la sua didattica: da Tosi e Mancini alla scuola di García e all'invenzione del laringoscopio" },
  { c: "organologia", t: "Il vibrato negli archi: da ornamento selettivo a suono di default — le prove nelle prime registrazioni" },
  { c: "organologia", t: "Il portamento vocale e strumentale: una prassi espressiva scomparsa documentata dai dischi acustici" },
  { c: "organologia", t: "La nascita del direttore d'orchestra moderno: da Berlioz a von Bülow, tra battuta, memoria e interpretazione" },

  // ------------------- NOTAZIONE E MUSICOLOGIA (25) -------------------
  { c: "musicologia", t: "I neumi: dalla notazione adiastematica in campo aperto al tetragramma guidoniano" },
  { c: "musicologia", t: "La semiologia gregoriana di Eugène Cardine: episema, liquescenza e i codici di San Gallo e Laon" },
  { c: "musicologia", t: "L'Ars cantus mensurabilis di Francone da Colonia: la notazione mensurale e il valore intrinseco delle figure" },
  { c: "musicologia", t: "La notazione mensurale bianca: legature, coloration e le trappole della trascrizione moderna" },
  { c: "musicologia", t: "Le intavolature per liuto: sistemi francese, italiano e tedesco a confronto" },
  { c: "musicologia", t: "Trascrivere la polifonia rinascimentale: stanghette, riduzione dei valori e le scelte che cambiano l'analisi" },
  { c: "musicologia", t: "La filologia musicale: stemma codicum, errori-guida e la critica del testo applicata ai manoscritti musicali" },
  { c: "musicologia", t: "Edizione critica vs Urtext: il mito del testo definitivo e il caso delle edizioni ottocentesche interventiste" },
  { c: "musicologia", t: "Gli abbozzi di Beethoven: le sketch studies e la genesi documentata della Sinfonia Eroica" },
  { c: "musicologia", t: "I cataloghi tematici: Köchel, BWV, Hoboken e i problemi di cronologia, autenticità e numerazione" },
  { c: "musicologia", t: "Falsi e attribuzioni dubbie: l'Adagio di Albinoni, i mottetti di Josquin e i metodi dell'attribuzionismo" },
  { c: "musicologia", t: "La New Musicology: Contemplating Music di Kerman e la critica al formalismo analitico" },
  { c: "musicologia", t: "Musicologia e studi di genere: le letture di Susan McClary e il dibattito sul canone" },
  { c: "musicologia", t: "Rockism e poptimism: la costruzione dell'autenticità nei popular music studies" },
  { c: "musicologia", t: "La topic theory: da Ratner a Monelle, i topoi del classicismo (caccia, militare, pastorale) e i loro limiti" },
  { c: "musicologia", t: "L'ermeneutica musicale di Lawrence Kramer: finestre ermeneutiche contro l'analisi formalista" },
  { c: "musicologia", t: "Text and Act di Richard Taruskin: l'autenticità del movimento early music come modernismo travestito" },
  { c: "musicologia", t: "L'archivistica sonora: cilindri di cera, 78 giri e le sfide della preservazione e digitalizzazione" },
  { c: "musicologia", t: "Il Music Information Retrieval: feature audio, corpus studies e i limiti dell'analisi computazionale della musica" },
  { c: "musicologia", t: "L'ecdotica dell'opera italiana: Philip Gossett e le edizioni critiche di Rossini e Verdi" },
  { c: "musicologia", t: "L'opera aperta di Umberto Eco e la musica indeterminata: Berio, Pousseur e la Terza Sonata di Boulez" },
  { c: "musicologia", t: "L'Affektenlehre barocca: la retorica musicale, le figure di Burmeister e il Der vollkommene Capellmeister di Mattheson" },
  { c: "musicologia", t: "Emotion and Meaning in Music di Leonard Meyer: aspettativa, inibizione e significato incorporato" },
  { c: "musicologia", t: "Adorno e la sociologia della musica: industria culturale, regressione dell'ascolto e la controversa critica al jazz" },
  { c: "musicologia", t: "R. Murray Schafer e l'ecologia acustica: soundscape, hi-fi e lo-fi, e il World Soundscape Project" },
];

const TOPICS_FACILE = [
  // ------------------------- TEORIA E ANALISI (25) -------------------------
  { c: "teoria", t: "Le note e il pentagramma: come funziona la scrittura musicale" },
  { c: "teoria", t: "La scala maggiore e la scala minore: cosa le distingue (e perché una suona allegra e l'altra triste)" },
  { c: "teoria", t: "Gli intervalli musicali: cosa sono e come si chiamano" },
  { c: "teoria", t: "Il ritmo e i tempi: la differenza tra 4/4, 3/4 e il valzer" },
  { c: "teoria", t: "Gli accordi maggiori e minori: come si costruiscono con tre note" },
  { c: "teoria", t: "Il giro di Do: la progressione di accordi più famosa della musica leggera" },
  { c: "teoria", t: "Le chiavi musicali: violino, basso e perché esistono" },
  { c: "teoria", t: "Le alterazioni: diesis, bemolle e bequadro" },
  { c: "teoria", t: "Il circolo delle quinte: la mappa segreta delle tonalità" },
  { c: "teoria", t: "Melodia, armonia e ritmo: i tre ingredienti della musica" },
  { c: "teoria", t: "Le dinamiche musicali: dal pianissimo al fortissimo" },
  { c: "teoria", t: "Le indicazioni di tempo: adagio, andante, allegro, presto" },
  { c: "teoria", t: "La sincope e il contrattempo: quando il ritmo ti sorprende" },
  { c: "teoria", t: "Il canone: come funziona 'Fra Martino' cantato a più voci" },
  { c: "teoria", t: "Strofa, ritornello e bridge: la forma della canzone pop" },
  { c: "teoria", t: "Cos'è una tonalità e cosa vuol dire 'cambiare tonalità'" },
  { c: "teoria", t: "La scala pentatonica: le cinque note che suonano bene ovunque" },
  { c: "teoria", t: "Il basso ostinato: quando lo stesso giro si ripete all'infinito (dal Canone di Pachelbel al pop)" },
  { c: "teoria", t: "Le voci del coro: soprano, contralto, tenore e basso" },
  { c: "teoria", t: "Cos'è un'ottava e perché le note a un certo punto 'ricominciano'" },
  { c: "teoria", t: "Il metronomo: a cosa serve, chi l'ha inventato e i BPM di oggi" },
  { c: "teoria", t: "Legato e staccato: i modi di collegare (o separare) le note" },
  { c: "teoria", t: "Cos'è un arpeggio e dove lo senti tutti i giorni senza saperlo" },
  { c: "teoria", t: "Consonanza e dissonanza: perché certe note insieme 'stridono'" },
  { c: "teoria", t: "Il solfeggio: cos'è, a cosa serve e perché fa paura a tutti" },

  // ------------------------ STORIA DELLA MUSICA (25) ------------------------
  { c: "storia", t: "La vita di Mozart: il bambino prodigio che stupì l'Europa" },
  { c: "storia", t: "Beethoven e la sordità: comporre senza sentire" },
  { c: "storia", t: "Johann Sebastian Bach: il grande papà della musica (e di venti figli)" },
  { c: "storia", t: "Vivaldi e Le Quattro Stagioni: il prete rosso di Venezia" },
  { c: "storia", t: "Il canto gregoriano: la musica dei monaci medievali" },
  { c: "storia", t: "Chopin: il poeta del pianoforte" },
  { c: "storia", t: "Verdi e il Risorgimento: quando l'opera divenne un simbolo dell'Italia" },
  { c: "storia", t: "Puccini e le sue eroine: Tosca, Butterfly e Turandot" },
  { c: "storia", t: "Rossini: Il barbiere di Siviglia e il misterioso ritiro a 37 anni" },
  { c: "storia", t: "Čajkovskij e i balletti: Lo Schiaccianoci e Il lago dei cigni" },
  { c: "storia", t: "La nascita dell'opera lirica in Italia intorno al 1600" },
  { c: "storia", t: "Paganini: il violinista 'del diavolo'" },
  { c: "storia", t: "Haydn, il 'papà della sinfonia': una vita al servizio dei principi" },
  { c: "storia", t: "Schubert e i suoi Lieder: canzoni d'autore dell'Ottocento" },
  { c: "storia", t: "Debussy: la musica che dipinge il mare e la luna" },
  { c: "storia", t: "Stravinskij e lo scandalo della Sagra della primavera: la rissa a teatro del 1913" },
  { c: "storia", t: "La musica nel Medioevo: trovatori, menestrelli e castelli" },
  { c: "storia", t: "Dal clavicembalo al pianoforte: chi è arrivato prima e cosa cambia" },
  { c: "storia", t: "Le compositrici dimenticate: Clara Schumann e Fanny Mendelssohn" },
  { c: "storia", t: "L'orchestra: com'è nata e come è diventata così grande" },
  { c: "storia", t: "Wagner e le sue opere-fiume: quattro serate per un solo racconto" },
  { c: "storia", t: "Il Romanticismo in musica: quando i sentimenti presero il comando" },
  { c: "storia", t: "Il Barocco musicale: chiese dorate, virtuosismi e meraviglia" },
  { c: "storia", t: "Mahler e le sinfonie giganti: mille musicisti sul palco" },
  { c: "storia", t: "La Nona di Beethoven e l'Inno alla gioia: da Vienna all'Europa unita" },

  // --------------------- ARMONIA E COMPOSIZIONE (25) ---------------------
  { c: "composizione", t: "Come si scrive una canzone: strofa, ritornello e la scintilla iniziale" },
  { c: "composizione", t: "Il tema con variazioni: la stessa melodia travestita in mille modi" },
  { c: "composizione", t: "La forma sonata spiegata semplice: presentazione, avventura e ritorno a casa" },
  { c: "composizione", t: "Il rondò: il ritornello che torna sempre" },
  { c: "composizione", t: "Cos'è una fuga: l'inseguimento tra le voci" },
  { c: "composizione", t: "L'inno di Mameli: chi l'ha scritto, quando e com'è fatto" },
  { c: "composizione", t: "Comporre con i loop: come nasce un beat al computer" },
  { c: "composizione", t: "La colonna sonora: come la musica racconta un film" },
  { c: "composizione", t: "John Williams: i temi di Star Wars, Indiana Jones e Harry Potter" },
  { c: "composizione", t: "Ennio Morricone e il suono del western all'italiana" },
  { c: "composizione", t: "Cos'è l'improvvisazione musicale: inventare sul momento" },
  { c: "composizione", t: "Il jingle pubblicitario: perché ti resta in testa" },
  { c: "composizione", t: "Gli earworm: la scienza delle canzoni che non escono dalla testa" },
  { c: "composizione", t: "L'hook: il gancio segreto delle hit pop" },
  { c: "composizione", t: "Scrivere per la voce: perché certe canzoni sono impossibili da cantare" },
  { c: "composizione", t: "L'arrangiamento: la stessa canzone in mille vestiti diversi" },
  { c: "composizione", t: "Cover e remix: rifare la musica degli altri (e quando è arte)" },
  { c: "composizione", t: "Il duetto: l'arte di scrivere per due voci" },
  { c: "composizione", t: "Musica e matematica: pattern, simmetrie e giochi di numeri" },
  { c: "composizione", t: "Il crescendo: come si costruisce l'emozione in un brano" },
  { c: "composizione", t: "Il contrappunto spiegato a tutti: più melodie che convivono" },
  { c: "composizione", t: "Le ninne nanne: perché funzionano in tutto il mondo allo stesso modo" },
  { c: "composizione", t: "Il leitmotiv: il tema musicale che identifica un personaggio (dallo Squalo a Dart Fener)" },
  { c: "composizione", t: "Comporre al computer: cos'è una DAW e come si usa" },
  { c: "composizione", t: "L'Auto-Tune: cos'è, come funziona e come ha cambiato la musica pop" },

  // --------------------- GENERI E POPULAR MUSIC (25) ---------------------
  { c: "generi", t: "Il rock and roll: Elvis Presley e la nascita di un mito" },
  { c: "generi", t: "I Beatles: perché quattro ragazzi di Liverpool hanno cambiato tutto" },
  { c: "generi", t: "Il jazz: da New Orleans alla conquista del mondo" },
  { c: "generi", t: "Il blues: dodici battute di malinconia che hanno generato tutto il resto" },
  { c: "generi", t: "Il rap: come è nato nelle feste di quartiere del Bronx" },
  { c: "generi", t: "Il reggae e Bob Marley: la musica della Giamaica" },
  { c: "generi", t: "La disco music: gli anni della febbre del sabato sera" },
  { c: "generi", t: "Il punk: tre accordi e tanta rabbia" },
  { c: "generi", t: "L'heavy metal: dai Black Sabbath ai giorni nostri" },
  { c: "generi", t: "La musica country: la voce dell'America rurale" },
  { c: "generi", t: "Il K-pop: come la Corea ha conquistato le classifiche mondiali" },
  { c: "generi", t: "La canzone napoletana: da 'O sole mio a Pino Daniele" },
  { c: "generi", t: "I cantautori italiani: De André, Battisti, Dalla e gli altri" },
  { c: "generi", t: "Il Festival di Sanremo: settant'anni di canzone italiana" },
  { c: "generi", t: "Il flamenco: la musica e la danza dell'Andalusia" },
  { c: "generi", t: "Il tango: la danza nata nei porti di Buenos Aires" },
  { c: "generi", t: "La bossa nova: la dolcezza del Brasile in punta di chitarra" },
  { c: "generi", t: "Il gospel: la musica delle chiese afroamericane" },
  { c: "generi", t: "House e techno: la musica elettronica da ballare" },
  { c: "generi", t: "Il grunge: Nirvana, Seattle e le camicie di flanella" },
  { c: "generi", t: "Il soul: Aretha Franklin, Stevie Wonder e la musica dell'anima" },
  { c: "generi", t: "Il funk: James Brown e il ritmo che comanda" },
  { c: "generi", t: "Il reggaeton: da Porto Rico alle classifiche di tutto il mondo" },
  { c: "generi", t: "La trap: come è cambiato il rap negli ultimi anni" },
  { c: "generi", t: "Il musical: da Broadway a Mamma Mia!, quando il teatro canta" },

  // -------------------------- ETNOMUSICOLOGIA (25) --------------------------
  { c: "etno", t: "Il didgeridoo: lo strumento millenario degli aborigeni australiani" },
  { c: "etno", t: "Il djembe e i tamburi africani: la musica come linguaggio di gruppo" },
  { c: "etno", t: "La musica indiana: il sitar, Ravi Shankar e l'incontro con i Beatles" },
  { c: "etno", t: "Il gamelan: le orchestre di gong e metallofoni dell'Indonesia" },
  { c: "etno", t: "La cornamusa scozzese: come funziona e perché suona così" },
  { c: "etno", t: "Il flauto di Pan delle Ande: la musica delle montagne sudamericane" },
  { c: "etno", t: "La musica irlandese: violini, danze e sessioni nei pub" },
  { c: "etno", t: "Il canto a gola degli Inuit: un gioco musicale tra due voci" },
  { c: "etno", t: "Il klezmer: la musica delle feste ebraiche dell'Est Europa" },
  { c: "etno", t: "Il bouzouki e il sirtaki: i suoni della Grecia" },
  { c: "etno", t: "La balalaika e i cori russi" },
  { c: "etno", t: "L'ukulele: la piccola chitarra delle Hawaii che ha conquistato il mondo" },
  { c: "etno", t: "Le launeddas sarde: tre canne e un solo, lunghissimo fiato" },
  { c: "etno", t: "La pizzica salentina e la taranta: la musica che 'curava' il morso del ragno" },
  { c: "etno", t: "Lo jodel: il canto che rimbalza tra le montagne" },
  { c: "etno", t: "I mariachi messicani: trombe, chitarre e sombreri" },
  { c: "etno", t: "La samba e il carnevale di Rio" },
  { c: "etno", t: "L'oud e la musica araba: il nonno del liuto e della chitarra" },
  { c: "etno", t: "Il taiko: i grandi tamburi del Giappone" },
  { c: "etno", t: "La kora e i griot: i cantastorie dell'Africa occidentale" },
  { c: "etno", t: "Il canto difonico della Mongolia: due suoni con una sola voce" },
  { c: "etno", t: "Lo steel drum di Trinidad: fare musica con i bidoni del petrolio" },
  { c: "etno", t: "La musica balcanica: ottoni scatenati e ritmi che sembrano inciampare" },
  { c: "etno", t: "La musica hawaiana e la chitarra slide" },
  { c: "etno", t: "I canti di lavoro: dalle mondine italiane ai campi di cotone" },

  // --------------------- ACUSTICA E PSICOACUSTICA (25) ---------------------
  { c: "acustica", t: "Cos'è il suono: vibrazioni che viaggiano nell'aria" },
  { c: "acustica", t: "L'eco: perché in montagna la voce ritorna" },
  { c: "acustica", t: "Suoni acuti e gravi: cos'è la frequenza" },
  { c: "acustica", t: "Il volume e i decibel: quanto è forte un concerto?" },
  { c: "acustica", t: "Il timbro: perché la stessa nota suona diversa su piano e chitarra" },
  { c: "acustica", t: "Come funziona l'orecchio umano: il viaggio del suono fino al cervello" },
  { c: "acustica", t: "Ultrasuoni e infrasuoni: i suoni che non sentiamo (ma i pipistrelli sì)" },
  { c: "acustica", t: "Perché la nostra voce registrata ci sembra strana" },
  { c: "acustica", t: "L'acustica dei teatri: perché si sente bene anche in ultima fila" },
  { c: "acustica", t: "La cassa armonica: perché la chitarra ha un buco in mezzo" },
  { c: "acustica", t: "Come fa una corda a produrre un suono" },
  { c: "acustica", t: "Il diapason: l'oggetto che dà il La a tutta l'orchestra" },
  { c: "acustica", t: "Perché l'elio rende la voce da paperino" },
  { c: "acustica", t: "L'effetto Doppler: perché la sirena dell'ambulanza cambia suono quando passa" },
  { c: "acustica", t: "Il rumore bianco: cos'è e perché aiuta a dormire" },
  { c: "acustica", t: "Le cuffie a cancellazione di rumore: come fanno a spegnere il mondo" },
  { c: "acustica", t: "Il microfono: come trasforma la voce in elettricità" },
  { c: "acustica", t: "Vinile, CD e streaming: come si registra e si ascolta il suono" },
  { c: "acustica", t: "Perché le unghie sulla lavagna ci fanno rabbrividire" },
  { c: "acustica", t: "La musica fa crescere le piante? Cosa dice davvero la scienza" },
  { c: "acustica", t: "L'orecchio assoluto: il superpotere di riconoscere le note al volo" },
  { c: "acustica", t: "Perché cantare sotto la doccia sembra sempre più bello" },
  { c: "acustica", t: "I brividi da musica: perché una canzone ci fa venire la pelle d'oca" },
  { c: "acustica", t: "Musica e memoria: perché ricordiamo le canzoni dell'infanzia" },
  { c: "acustica", t: "Il canto delle balene: la musica più antica dell'oceano" },

  // ---------------- ORGANOLOGIA E PRASSI ESECUTIVA (25) ----------------
  { c: "organologia", t: "Gli strumenti dell'orchestra: le quattro famiglie" },
  { c: "organologia", t: "Il violino: com'è fatto e perché uno Stradivari vale milioni" },
  { c: "organologia", t: "Il pianoforte: cosa succede davvero quando premi un tasto" },
  { c: "organologia", t: "Chitarra classica, acustica ed elettrica: le differenze" },
  { c: "organologia", t: "La batteria: da quali tamburi e piatti è composta" },
  { c: "organologia", t: "Il flauto dolce e il flauto traverso: cugini ma non gemelli" },
  { c: "organologia", t: "La tromba e il trombone: come funzionano gli ottoni" },
  { c: "organologia", t: "L'organo a canne: il gigante delle chiese" },
  { c: "organologia", t: "L'arpa: quante corde ha e come si fa a non perdersi" },
  { c: "organologia", t: "Il sassofono: la geniale invenzione del signor Sax" },
  { c: "organologia", t: "Il clarinetto e l'oboe: i legni e le loro ance" },
  { c: "organologia", t: "Il violoncello e il contrabbasso: le voci gravi degli archi" },
  { c: "organologia", t: "La fisarmonica: il pianoforte a soffietto" },
  { c: "organologia", t: "Il basso elettrico: il motore nascosto di ogni band" },
  { c: "organologia", t: "Il sintetizzatore: creare suoni mai sentiti prima" },
  { c: "organologia", t: "Il theremin: lo strumento che si suona senza toccarlo" },
  { c: "organologia", t: "Triangolo, tamburello e maracas: le piccole percussioni" },
  { c: "organologia", t: "Il mandolino: l'Italia in otto corde" },
  { c: "organologia", t: "Il beatbox: quando la voce diventa una batteria" },
  { c: "organologia", t: "Il direttore d'orchestra: cosa fa davvero con quella bacchetta" },
  { c: "organologia", t: "Come si accorda uno strumento (e perché si scorda)" },
  { c: "organologia", t: "Kazoo e melodica: gli strumenti 'giocattolo' che sono strumenti veri" },
  { c: "organologia", t: "Il carillon e le scatole musicali: la musica meccanica" },
  { c: "organologia", t: "Il DJ e i giradischi: l'arte dello scratch" },
  { c: "organologia", t: "L'orchestra di Cateura: strumenti costruiti con i rifiuti" },

  // ------------------- NOTAZIONE E MUSICOLOGIA (25) -------------------
  { c: "musicologia", t: "Come si legge uno spartito: le basi per iniziare" },
  { c: "musicologia", t: "Breve storia della notazione: perché la musica si scrive proprio così" },
  { c: "musicologia", t: "I diritti d'autore nella musica: chi guadagna da una canzone" },
  { c: "musicologia", t: "Il plagio musicale: quando due canzoni si somigliano troppo" },
  { c: "musicologia", t: "Come funziona un conservatorio: cosa si studia e come si entra" },
  { c: "musicologia", t: "Il mestiere del liutaio: costruire strumenti a mano" },
  { c: "musicologia", t: "Cosa fa un produttore musicale" },
  { c: "musicologia", t: "Come nasce un disco: dallo studio di registrazione allo streaming" },
  { c: "musicologia", t: "Le classifiche musicali: come si misurano gli ascolti" },
  { c: "musicologia", t: "I Grammy e gli altri grandi premi della musica" },
  { c: "musicologia", t: "La musica nei videogiochi: da Super Mario a oggi" },
  { c: "musicologia", t: "Le sigle dei cartoni animati: piccoli capolavori italiani" },
  { c: "musicologia", t: "La musica in pubblicità: perché funziona così bene" },
  { c: "musicologia", t: "La musicoterapia: curare e stare meglio con i suoni" },
  { c: "musicologia", t: "La musica negli stadi: inni, cori e riti sportivi" },
  { c: "musicologia", t: "Le tribute band: perché esistono e perché piacciono" },
  { c: "musicologia", t: "Il karaoke: storia di un fenomeno nato in Giappone" },
  { c: "musicologia", t: "Lo Zecchino d'Oro e le canzoni per bambini" },
  { c: "musicologia", t: "I talent show musicali: come hanno cambiato il mercato della musica" },
  { c: "musicologia", t: "Il ritorno del vinile: perché piace ancora nell'era digitale" },
  { c: "musicologia", t: "Lo streaming musicale: come Spotify paga (poco) gli artisti" },
  { c: "musicologia", t: "Cosa c'è dietro un concerto: palchi, tour e roadie" },
  { c: "musicologia", t: "L'arte della playlist: mettere le canzoni nell'ordine giusto" },
  { c: "musicologia", t: "La colonna sonora della nostra vita: musica, ricordi e nostalgia" },
  { c: "musicologia", t: "Chi sono i musicologi: come si studia la musica all'università" },
];

const TOPICS_INTERMEDIO = [
  // ------------------------- TEORIA E ANALISI (25) -------------------------
  { c: "teoria", t: "La forma sonata: esposizione, sviluppo e ripresa (con un esempio alla mano)" },
  { c: "teoria", t: "Il circolo delle quinte e le armature di chiave: come sono collegati davvero" },
  { c: "teoria", t: "Le cadenze: perfetta, plagale, sospesa e d'inganno" },
  { c: "teoria", t: "I gradi della scala e le loro funzioni: tonica, dominante e sottodominante" },
  { c: "teoria", t: "Le tre scale minori: naturale, armonica e melodica (e perché esistono)" },
  { c: "teoria", t: "I modi: dorico, frigio, lidio, misolidio e dove si nascondono nel rock e nel pop" },
  { c: "teoria", t: "Gli accordi di settima: costruzione, tipi e uso" },
  { c: "teoria", t: "La modulazione: come si cambia tonalità dentro un brano senza far sentire lo strappo" },
  { c: "teoria", t: "Il basso continuo: cos'era, come si leggevano i numeri e chi lo suonava" },
  { c: "teoria", t: "Le regole base del contrappunto: comporre a due voci senza errori" },
  { c: "teoria", t: "La struttura del blues in dodici battute: armonia, forma e varianti" },
  { c: "teoria", t: "Analizzare una canzone pop: gradi, giri armonici e prestiti modali" },
  { c: "teoria", t: "Tempi composti e tempi dispari: 6/8, 5/4 e 7/8 con esempi celebri" },
  { c: "teoria", t: "La poliritmia: due ritmi diversi nello stesso momento" },
  { c: "teoria", t: "Il trasporto: portare un brano in un'altra tonalità (e perché i cantanti lo chiedono)" },
  { c: "teoria", t: "Armonizzare una melodia: le prime regole e gli errori classici" },
  { c: "teoria", t: "Note di passaggio, ritardi e appoggiature: le note 'estranee' all'accordo" },
  { c: "teoria", t: "Il pedale di tonica e di dominante: la nota che resta ferma sotto tutto" },
  { c: "teoria", t: "Il tritono: storia e usi dell'intervallo 'del diavolo'" },
  { c: "teoria", t: "La scala cromatica e il cromatismo nella musica dell'Ottocento" },
  { c: "teoria", t: "I rivolti degli accordi e l'arte di far cantare il basso" },
  { c: "teoria", t: "Tema e variazioni: le tecniche per trasformare una melodia" },
  { c: "teoria", t: "La sesta napoletana: l'accordo che porta il nome di una città" },
  { c: "teoria", t: "Il II-V-I: la progressione che regge tutto il jazz" },
  { c: "teoria", t: "Leggere una partitura d'orchestra: ordine degli strumenti e strumenti traspositori" },

  // ------------------------ STORIA DELLA MUSICA (25) ------------------------
  { c: "storia", t: "La scuola fiamminga: la grande polifonia del Quattrocento" },
  { c: "storia", t: "Palestrina e la Controriforma: la leggenda della messa che 'salvò' la polifonia" },
  { c: "storia", t: "Monteverdi: dal madrigale all'Orfeo, la nascita del teatro in musica" },
  { c: "storia", t: "Il concerto grosso: Corelli, Händel e il gioco dei contrasti" },
  { c: "storia", t: "Bach e il Clavicembalo ben temperato: perché è una pietra miliare" },
  { c: "storia", t: "Händel a Londra: opere italiane, oratori inglesi e il Messiah" },
  { c: "storia", t: "Lo stile classico: Haydn, Mozart e l'equilibrio delle forme" },
  { c: "storia", t: "Il Don Giovanni di Mozart: commedia e tragedia nella stessa opera" },
  { c: "storia", t: "Le nove sinfonie di Beethoven: il percorso di una rivoluzione" },
  { c: "storia", t: "Schumann critico musicale: la nascita della critica romantica" },
  { c: "storia", t: "Liszt: il virtuosismo, le trascrizioni e l'invenzione del recital" },
  { c: "storia", t: "Brahms contro Wagner: le due strade della musica di fine Ottocento" },
  { c: "storia", t: "L'opera italiana dell'Ottocento: da Bellini e Donizetti a Verdi" },
  { c: "storia", t: "Il poema sinfonico: raccontare storie senza parole" },
  { c: "storia", t: "Le scuole nazionali: Grieg, Smetana, Dvořák e la musica come identità" },
  { c: "storia", t: "Debussy e Ravel: due 'impressionisti' molto diversi tra loro" },
  { c: "storia", t: "Mahler: la sinfonia come un mondo intero" },
  { c: "storia", t: "Schoenberg e l'addio alla tonalità: perché e come" },
  { c: "storia", t: "Stravinskij camaleonte: periodo russo, neoclassico e seriale" },
  { c: "storia", t: "Il Novecento italiano: Respighi, Casella e la generazione dell'Ottanta" },
  { c: "storia", t: "Gershwin e la Rhapsody in Blue: quando il jazz incontrò la classica" },
  { c: "storia", t: "Musica e dittature: censura e propaganda nel Novecento europeo" },
  { c: "storia", t: "Britten e l'opera del dopoguerra: Peter Grimes e il ritorno del teatro musicale" },
  { c: "storia", t: "Il minimalismo americano: Reich, Glass e la ripetizione come stile" },
  { c: "storia", t: "La musica colta oggi: cosa compongono i compositori del XXI secolo" },

  // --------------------- ARMONIA E COMPOSIZIONE (25) ---------------------
  { c: "composizione", t: "La fuga: soggetto, risposta e come seguirla all'ascolto" },
  { c: "composizione", t: "L'orchestrazione: l'arte di assegnare le note agli strumenti giusti" },
  { c: "composizione", t: "Scrivere un corale a quattro voci: le regole principali della condotta delle parti" },
  { c: "composizione", t: "La suite barocca: allemanda, corrente, sarabanda e giga" },
  { c: "composizione", t: "Il concerto solistico: la forma, il dialogo e il ruolo della cadenza" },
  { c: "composizione", t: "Il Lied romantico: musica e poesia in una stanza" },
  { c: "composizione", t: "Il quartetto d'archi: perché è considerato il banco di prova dei compositori" },
  { c: "composizione", t: "La dodecafonia spiegata: comporre con tutte e dodici le note" },
  { c: "composizione", t: "La musica a programma: sinfonie che raccontano storie" },
  { c: "composizione", t: "Il leitmotiv nel Ring di Wagner: come funziona davvero" },
  { c: "composizione", t: "Comporre una colonna sonora: temi, spotting e sincronizzazione" },
  { c: "composizione", t: "Il sound design: quando il rumore diventa musica" },
  { c: "composizione", t: "Il campionamento come composizione: dalla musique concrète all'hip-hop" },
  { c: "composizione", t: "L'improvvisazione jazz: scale, accordi e come si costruisce un assolo" },
  { c: "composizione", t: "L'arrangiamento per big band: sezioni, voicing e riff" },
  { c: "composizione", t: "Scrivere per coro: tessiture, respiri e rapporto col testo" },
  { c: "composizione", t: "Reinventare uno standard: l'arte della variazione nel jazz" },
  { c: "composizione", t: "Il minimalismo in pratica: pattern, sfasamenti e processi graduali" },
  { c: "composizione", t: "La musica aleatoria: quando il caso entra nella partitura" },
  { c: "composizione", t: "La sintesi del suono: sottrattiva, additiva e FM spiegate" },
  { c: "composizione", t: "Il remix come forma d'arte: storia e tecniche" },
  { c: "composizione", t: "L'armonia modale nel pop e nel rock: oltre il maggiore e il minore" },
  { c: "composizione", t: "Il walking bass: costruire la linea di contrabbasso nel jazz" },
  { c: "composizione", t: "Le armonie vocali dei Beach Boys e dei Beatles: come sono fatte" },
  { c: "composizione", t: "La musica generativa: comporre sistemi invece che brani (da Eno in poi)" },

  // --------------------- GENERI E POPULAR MUSIC (25) ---------------------
  { c: "generi", t: "Dal ragtime allo swing: la prima grande storia del jazz" },
  { c: "generi", t: "Il bebop: la rivoluzione di Charlie Parker e Dizzy Gillespie" },
  { c: "generi", t: "Miles Davis: quattro volte pioniere (cool, modale, fusion, elettrico)" },
  { c: "generi", t: "La British Invasion: il beat inglese conquista l'America" },
  { c: "generi", t: "Il rock progressivo: Pink Floyd, Genesis e le suite di venti minuti" },
  { c: "generi", t: "Bob Dylan e la canzone di protesta americana" },
  { c: "generi", t: "Il Motown sound: la fabbrica dei successi di Detroit" },
  { c: "generi", t: "Ska e rocksteady: cosa c'era prima del reggae" },
  { c: "generi", t: "La disco e la nascita della club culture: DJ, dancefloor e liberazione" },
  { c: "generi", t: "Post-punk e new wave: cosa successe dopo il punk" },
  { c: "generi", t: "La golden age dell'hip-hop: da Public Enemy a A Tribe Called Quest" },
  { c: "generi", t: "Grunge e rock alternativo: gli anni Novanta americani" },
  { c: "generi", t: "Il britpop: Oasis contro Blur e l'orgoglio inglese" },
  { c: "generi", t: "Da Kraftwerk alla EDM: mezzo secolo di musica elettronica" },
  { c: "generi", t: "Le famiglie del metal: thrash, doom, power, black e death" },
  { c: "generi", t: "La world music: nascita e critiche di un'etichetta discografica" },
  { c: "generi", t: "La canzone d'autore italiana: le scuole di Genova, Bologna e Roma" },
  { c: "generi", t: "Il pop italiano dagli urlatori all'indie: sessant'anni di trasformazioni" },
  { c: "generi", t: "Il nuovo flamenco: Paco de Lucía e Camarón de la Isla" },
  { c: "generi", t: "La salsa: New York, Porto Rico, Cuba e la Fania Records" },
  { c: "generi", t: "Dall'afrobeat all'afropop: da Fela Kuti a Burna Boy" },
  { c: "generi", t: "Il reggaeton e la musica urbana latina: il ritmo dembow alla conquista del mondo" },
  { c: "generi", t: "Il K-pop come industria: trainee, fandom e catene di produzione" },
  { c: "generi", t: "Il jazz europeo e italiano: una voce autonoma dall'America" },
  { c: "generi", t: "Il neo-soul e la rinascita del soul: da D'Angelo ad Amy Winehouse" },

  // -------------------------- ETNOMUSICOLOGIA (25) --------------------------
  { c: "etno", t: "La musica classica indiana: raga, tala e i due sistemi (hindustani e carnatico)" },
  { c: "etno", t: "Il gamelan e l'Occidente: com'è fatto e come influenzò Debussy" },
  { c: "etno", t: "La musica araba: il sistema dei maqam e i quarti di tono" },
  { c: "etno", t: "L'Africa occidentale: griot, kora e la poliritmia" },
  { c: "etno", t: "Il flamenco dall'interno: palos, compás e il duende" },
  { c: "etno", t: "La musica andina: strumenti, scale e la storia di El cóndor pasa" },
  { c: "etno", t: "Il fado: storia, stili e la voce di Amália Rodrigues" },
  { c: "etno", t: "Il klezmer e la musica yiddish: la colonna sonora di una diaspora" },
  { c: "etno", t: "I ritmi asimmetrici dei Balcani: 7/8, 9/8 e le bande di ottoni" },
  { c: "etno", t: "Il canto difonico: come si producono due note con una sola voce" },
  { c: "etno", t: "Le polifonie tradizionali italiane: il canto a tenore e il canto a più voci" },
  { c: "etno", t: "Taranta e tarantismo: la musica come cura nel Salento di De Martino" },
  { c: "etno", t: "La musica celtica: sessioni, danze e il grande revival" },
  { c: "etno", t: "Son e rumba cubana: le radici di tutta la musica latina" },
  { c: "etno", t: "La samba: dalle case delle tie baiane alle scuole di samba" },
  { c: "etno", t: "Calipso e soca: Trinidad, il carnevale e la satira cantata" },
  { c: "etno", t: "La musica tradizionale giapponese: koto, shakuhachi e shamisen" },
  { c: "etno", t: "Il pansori e la musica tradizionale coreana" },
  { c: "etno", t: "La musica turca: dal saz alla musica classica ottomana" },
  { c: "etno", t: "Il rebetiko: il 'blues' greco dei porti e dei bassifondi" },
  { c: "etno", t: "La musica gitana d'Europa: dal jazz manouche di Django alle bande balcaniche" },
  { c: "etno", t: "I canti delle mondine e il lavoro nei campi: l'etnomusicologia italiana" },
  { c: "etno", t: "Alan Lomax e la caccia ai canti popolari: le grandi raccolte sul campo" },
  { c: "etno", t: "La musica aborigena australiana: didgeridoo e songlines" },
  { c: "etno", t: "Cos'è l'etnomusicologia: la ricerca sul campo e i suoi metodi" },

  // --------------------- ACUSTICA E PSICOACUSTICA (25) ---------------------
  { c: "acustica", t: "La serie degli armonici: perché esiste e cosa determina" },
  { c: "acustica", t: "Frequenza e altezza: la matematica dietro le note e le ottave" },
  { c: "acustica", t: "Il temperamento equabile: il compromesso su cui si basa il pianoforte" },
  { c: "acustica", t: "I battimenti: perché due note quasi uguali 'ondeggiano' (e come si accorda con le orecchie)" },
  { c: "acustica", t: "Anatomia del timbro: attacco, inviluppo e spettro di un suono" },
  { c: "acustica", t: "L'acustica architettonica: riverbero, materiali e la forma delle sale" },
  { c: "acustica", t: "Come funziona un altoparlante (e perché le casse hanno due o tre coni)" },
  { c: "acustica", t: "La compressione audio: cosa si perde davvero tra un CD e un MP3" },
  { c: "acustica", t: "La loudness war: la 'guerra del volume' nella musica registrata" },
  { c: "acustica", t: "Stereo, surround e audio spaziale: come si costruisce lo spazio sonoro" },
  { c: "acustica", t: "La voce umana: corde vocali, formanti e registri" },
  { c: "acustica", t: "La fisiologia del canto: perché le voci sono tutte diverse" },
  { c: "acustica", t: "La risonanza: dal bicchiere che si rompe al ponte che oscilla" },
  { c: "acustica", t: "Psicoacustica di base: il mascheramento e le principali illusioni sonore" },
  { c: "acustica", t: "L'effetto cocktail party: come isoliamo una voce in mezzo al rumore" },
  { c: "acustica", t: "Musica e cervello: cosa si attiva quando ascoltiamo" },
  { c: "acustica", t: "Perché la musica fa ballare: il ritmo, il corpo e il groove" },
  { c: "acustica", t: "Orecchio relativo e orecchio assoluto: cosa si può allenare" },
  { c: "acustica", t: "Sordità e musica: percepire il suono col corpo e gli impianti cocleari" },
  { c: "acustica", t: "Rumore e salute: quanto volume è troppo e come proteggersi" },
  { c: "acustica", t: "Gli infrasuoni dell'organo: il suono che si sente con lo stomaco" },
  { c: "acustica", t: "Il mito dei 432 Hz: cosa dice davvero la scienza sull'accordatura" },
  { c: "acustica", t: "Come si misura l'acustica di una sala da concerto" },
  { c: "acustica", t: "Il larsen: perché il microfono fischia e come si evita" },
  { c: "acustica", t: "Analogico e digitale: campionamento, bit e la conversione del suono" },

  // ---------------- ORGANOLOGIA E PRASSI ESECUTIVA (25) ----------------
  { c: "organologia", t: "La famiglia degli archi: costruzione, arco e tecniche (pizzicato, armonici, sordina)" },
  { c: "organologia", t: "Dentro il pianoforte: martelli, smorzatori e i tre pedali" },
  { c: "organologia", t: "Gli ottoni: come pistoni e coulisse cambiano le note" },
  { c: "organologia", t: "I legni: ance semplici, ance doppie e imboccature a confronto" },
  { c: "organologia", t: "L'organo a canne: registri, manuali e l'arte di 'costruire' il suono" },
  { c: "organologia", t: "Clavicembalo, clavicordo e fortepiano: le tastiere prima del pianoforte" },
  { c: "organologia", t: "La chitarra elettrica: pickup, amplificatore e la nascita della distorsione" },
  { c: "organologia", t: "Dal contrabbasso al basso elettrico: storia di un passaggio di testimone" },
  { c: "organologia", t: "La batteria moderna: storia di uno strumento assemblato pezzo per pezzo" },
  { c: "organologia", t: "Il sintetizzatore: oscillatori, filtri e inviluppi spiegati" },
  { c: "organologia", t: "Il campionatore: da macchina di nicchia a fondamento dell'hip-hop" },
  { c: "organologia", t: "Suonare Bach su strumenti d'epoca: il senso della prassi storica" },
  { c: "organologia", t: "La liuteria: come nasce un violino, dal legno alla vernice" },
  { c: "organologia", t: "Le percussioni orchestrali: timpani, xilofono e le loro tecniche" },
  { c: "organologia", t: "L'arpa moderna: i sette pedali e come funzionano" },
  { c: "organologia", t: "Gli strumenti traspositori: perché il clarinetto legge Do e suona Si bemolle" },
  { c: "organologia", t: "La classificazione delle voci: soprano, mezzosoprano, tenore, baritono, basso" },
  { c: "organologia", t: "Vibrato, glissando e gli effetti espressivi sugli strumenti" },
  { c: "organologia", t: "Il suono dal vivo: mixer, monitor e il mestiere del fonico" },
  { c: "organologia", t: "Lo studio di registrazione: microfoni, banco e la catena del suono" },
  { c: "organologia", t: "Il MIDI: il linguaggio che fa parlare gli strumenti elettronici" },
  { c: "organologia", t: "Sitar, kalimba e steel drum: strumenti 'lontani' entrati nel pop" },
  { c: "organologia", t: "La manutenzione degli strumenti: corde, ance, umidità e accordature" },
  { c: "organologia", t: "Theremin e onde Martenot: suonare l'elettricità" },
  { c: "organologia", t: "La direzione d'orchestra: gesto, prove e interpretazione" },

  // ------------------- NOTAZIONE E MUSICOLOGIA (25) -------------------
  { c: "musicologia", t: "Leggere una partitura d'orchestra: la mappa completa" },
  { c: "musicologia", t: "La notazione musicale nella storia: dai neumi al computer" },
  { c: "musicologia", t: "Cos'è un'edizione critica e perché gli spartiti non sono tutti uguali" },
  { c: "musicologia", t: "Mettere in musica un testo: prosodia, accenti e significato" },
  { c: "musicologia", t: "Gli strumenti di base dell'analisi musicale: come si 'smonta' un brano" },
  { c: "musicologia", t: "Bootleg, demo e outtake: le 'fonti' della popular music" },
  { c: "musicologia", t: "Il diritto d'autore musicale: SIAE, royalties e l'era dello streaming" },
  { c: "musicologia", t: "Il plagio musicale nei tribunali: i casi famosi e i criteri dei giudici" },
  { c: "musicologia", t: "La critica musicale: da Hanslick alle recensioni online" },
  { c: "musicologia", t: "La sociologia della musica: gusti, classi sociali e identità" },
  { c: "musicologia", t: "Musica e propaganda: gli usi politici della musica nella storia" },
  { c: "musicologia", t: "Le donne nella storia della musica: compositrici, interpreti e ostacoli" },
  { c: "musicologia", t: "Il canone musicale: chi decide quali opere sono 'capolavori'" },
  { c: "musicologia", t: "L'industria discografica: da Edison allo streaming, i grandi passaggi" },
  { c: "musicologia", t: "La radio e la musica: come ha cambiato per sempre l'ascolto" },
  { c: "musicologia", t: "Il videoclip: da MTV a YouTube, la musica che si guarda" },
  { c: "musicologia", t: "Musica e cinema: breve storia della colonna sonora" },
  { c: "musicologia", t: "Gli archivi sonori: nastri, dischi e la corsa alla digitalizzazione" },
  { c: "musicologia", t: "Musicologia storica ed etnomusicologia: due mestieri a confronto" },
  { c: "musicologia", t: "La musica nei rituali: sacro, festa e lutto nelle culture del mondo" },
  { c: "musicologia", t: "La musicoterapia: le evidenze scientifiche e le applicazioni cliniche" },
  { c: "musicologia", t: "I metodi dell'educazione musicale: Suzuki, Orff e Kodály a confronto" },
  { c: "musicologia", t: "Il mercato dei concerti: promoter, biglietti e l'economia dei festival" },
  { c: "musicologia", t: "Musica e intelligenza artificiale: le questioni aperte (da studiare senza usarla!)" },
  { c: "musicologia", t: "I popular music studies: quando il pop è entrato all'università" },
];

// ── Mazzo completo: 600 argomenti con livello ──
const TOPICS = [
  ...TOPICS_FACILE.map((t) => ({ ...t, l: "facile" })),
  ...TOPICS_INTERMEDIO.map((t) => ({ ...t, l: "intermedio" })),
  ...TOPICS_ESPERTO.map((t) => ({ ...t, l: "esperto" })),
];
