// ===================================================================
// Minuetto — database dei 200 argomenti
// 8 categorie × 25 argomenti, pensati per essere indagati su
// Google Scholar, JSTOR, RILM e letteratura accademica (non Wikipedia).
// ===================================================================

const CATEGORIES = {
  teoria:      { label: "Teoria e analisi",              emoji: "📐", color: "#7c6ff0" },
  storia:      { label: "Storia della musica",           emoji: "🏛️", color: "#e0709b" },
  composizione:{ label: "Armonia e composizione",        emoji: "✒️", color: "#4fa3a5" },
  generi:      { label: "Generi e popular music",        emoji: "🎸", color: "#e08f3c" },
  etno:        { label: "Etnomusicologia",               emoji: "🌍", color: "#5e9e58" },
  acustica:    { label: "Acustica e psicoacustica",      emoji: "🔬", color: "#4f7fd9" },
  organologia: { label: "Organologia e prassi esecutiva",emoji: "🎻", color: "#b0713a" },
  musicologia: { label: "Notazione e musicologia",       emoji: "📜", color: "#9a6bb5" },
};

const TOPICS = [
  // ------------------------- TEORIA E ANALISI (25) -------------------------
  { c: "teoria", t: "L'Ursatz nell'analisi schenkeriana: Urlinie, Bassbrechung e i livelli strutturali (foreground, middleground, background)" },
  { c: "teoria", t: "La teoria neo-riemanniana: le trasformazioni P, L, R e la navigazione del Tonnetz" },
  { c: "teoria", t: "La pitch-class set theory di Allen Forte: forma prima, vettore intervallare e relazioni Z" },
  { c: "teoria", t: "La Grundgestalt schoenberghiana e il principio della developing variation" },
  { c: "teoria", t: "La teoria delle funzioni armoniche di Hugo Riemann e il dualismo armonico: il problema del minore" },
  { c: "teoria", t: "Il partimento napoletano: apprendimento del contrappunto improvvisato nei conservatori del Settecento" },
  { c: "teoria", t: "La règle de l'octave: armonizzazione della scala nella prassi del basso continuo francese e italiano" },
  { c: "teoria", t: "Gli schemi galanti di Robert Gjerdingen: Prinner, Romanesca, Monte, Fonte e Ponte" },
  { c: "teoria", t: "La teoria delle funzioni formali di William Caplin: sentence, period e la tight-knit organization" },
  { c: "teoria", t: "La Sonata Theory di Hepokoski e Darcy: rotazioni, medial caesura e i cinque tipi di sonata" },
  { c: "teoria", t: "La modulazione enarmonica: la sesta tedesca riscritta come settima di dominante e i suoi usi da Schubert a Wolf" },
  { c: "teoria", t: "L'accordo di Tristano: un secolo e mezzo di analisi in conflitto (funzionale, appoggiatura, atonale, trasformazionale)" },
  { c: "teoria", t: "Tactus e proporzioni mensurali nella teoria rinascimentale: tempus, prolatio e i segni di proporzione" },
  { c: "teoria", t: "I modi ecclesiastici da Boezio al Dodecachordon di Glareano: autentici, plagali e i nuovi modi eolio e ionico" },
  { c: "teoria", t: "La solmisazione guidoniana: esacordi naturale, molle e duro, le mutazioni e il gamut medievale" },
  { c: "teoria", t: "Il concetto di consonanza da Pitagora a Zarlino: rapporti numerici, senario e la giustificazione della terza" },
  { c: "teoria", t: "Ipermetro e anacrusi strutturale: la teoria del fraseggio di William Rothstein" },
  { c: "teoria", t: "La Generative Theory of Tonal Music di Lerdahl e Jackendoff: riduzione time-span e riduzione prolongazionale" },
  { c: "teoria", t: "La teoria della proiezione metrica di Christopher Hasty: il metro come processo e non come griglia" },
  { c: "teoria", t: "La progressione omnibus e la condotta delle parti parsimoniosa nel cromatismo ottocentesco" },
  { c: "teoria", t: "Le clausole cantizans, tenorizans e basizans: la cadenza nella polifonia pre-tonale" },
  { c: "teoria", t: "La musica ficta: semitonia sotto-intesa, criteri editoriali e prassi esecutiva nella polifonia antica" },
  { c: "teoria", t: "La teoria del contorno melodico (contour theory) di Robert Morris e i c-segments" },
  { c: "teoria", t: "L'analisi paradigmatica di Nicolas Ruwet e la tripartizione semiotica di Jean-Jacques Nattiez" },
  { c: "teoria", t: "Tonicizzazione vs modulazione: dove finisce l'una e comincia l'altra secondo Schenker, Schoenberg e la teoria nordamericana" },

  // ------------------------ STORIA DELLA MUSICA (25) ------------------------
  { c: "storia", t: "L'Ars Nova francese: il Roman de Fauvel, Philippe de Vitry e la nuova notazione del Trecento" },
  { c: "storia", t: "L'Ars subtilior: la complessità ritmica estrema del Codex Chantilly e di Baude Cordier" },
  { c: "storia", t: "La scuola di Notre-Dame: organum duplum, clausulae sostitutive e i sei modi ritmici" },
  { c: "storia", t: "Il mottetto isoritmico da Machaut a Du Fay: talea, color e la panisoritmia" },
  { c: "storia", t: "La messa ciclica su cantus firmus: la tradizione dell'Homme armé da Du Fay a Palestrina" },
  { c: "storia", t: "Il madrigale italiano tardo: il cromatismo sperimentale di Gesualdo, Luzzaschi e l'arcicembalo di Vicentino" },
  { c: "storia", t: "La seconda pratica: la polemica Artusi-Monteverdi e la nascita della dissonanza espressiva" },
  { c: "storia", t: "La Camerata de' Bardi e la nascita dell'opera: recitar cantando, Peri, Caccini e il mito della tragedia greca" },
  { c: "storia", t: "La policoralità veneziana: i cori spezzati, i Gabrieli e l'acustica di San Marco" },
  { c: "storia", t: "La tragédie lyrique di Lully contro l'opera italiana: la Querelle des Bouffons del 1752" },
  { c: "storia", t: "Lo stile galante e l'Empfindsamkeit: la scuola napoletana e le fantasie di C.P.E. Bach" },
  { c: "storia", t: "La sinfonia pre-classica: la scuola di Mannheim, Sammartini e la questione delle origini della forma" },
  { c: "storia", t: "Il Beethoven tardo: le sonate op. 109-111 tra fuga, variazione e dissoluzione della forma sonata" },
  { c: "storia", t: "La Winterreise di Schubert come ciclo: coerenza tonale, Wanderer e la questione dell'unità" },
  { c: "storia", t: "La guerra dei romantici: Brahms e Hanslick contro la Neudeutsche Schule di Liszt e Wagner" },
  { c: "storia", t: "Il dramma musicale wagneriano: Leitmotiv, melodia infinita e la teoria del Gesamtkunstwerk" },
  { c: "storia", t: "Il Gruppo dei Cinque e il nazionalismo russo: orientalismo, modalità e il rifiuto del conservatorio" },
  { c: "storia", t: "La restaurazione del canto gregoriano a Solesmes: la querelle tra mensuralisti ed equalisti" },
  { c: "storia", t: "Il verismo musicale e la crisi della 'solita forma': drammaturgia e convenzioni nell'opera fin-de-siècle" },
  { c: "storia", t: "Jeux di Debussy: forma-momento, timbro e la modernità nascosta dell'ultimo Debussy" },
  { c: "storia", t: "La Seconda Scuola di Vienna: dall'atonalità libera di Erwartung al metodo dodecafonico del 1923" },
  { c: "storia", t: "Le Sacre du printemps: primitivismo, innovazione ritmica e la ricostruzione dello scandalo del 1913" },
  { c: "storia", t: "Il neoclassicismo tra le due guerre: Stravinskij, il rappel à l'ordre e la polemica con Schoenberg" },
  { c: "storia", t: "Šostakovič e il realismo socialista: il caso Lady Macbeth e l'articolo 'Caos invece di musica' del 1936" },
  { c: "storia", t: "I Ferienkurse di Darmstadt: serialismo integrale, alea e la frattura Cage-Boulez" },

  // --------------------- ARMONIA E COMPOSIZIONE (25) ---------------------
  { c: "composizione", t: "Le cinque specie di contrappunto nel Gradus ad Parnassum di Fux e la loro fortuna didattica" },
  { c: "composizione", t: "La fuga bachiana: soggetto, risposta reale e tonale, controsoggetto, stretto e i divertimenti" },
  { c: "composizione", t: "Il canone e le sue tipologie: per aumentazione, cancrizzante, a specchio ed enigmatico nell'Offerta Musicale" },
  { c: "composizione", t: "Il corale bachiano a quattro voci: condotta delle parti, note di passaggio e lo stile come corpus statistico" },
  { c: "composizione", t: "Il metodo dodecafonico: serie, matrice 12×12 e la combinatorialità esacordale di Milton Babbitt" },
  { c: "composizione", t: "La Klangfarbenmelodie: il terzo dei Cinque pezzi per orchestra op. 16 di Schoenberg e la melodia di timbri" },
  { c: "composizione", t: "Stockhausen e la Momentform: la tecnica dei gruppi da Gruppen a Momente" },
  { c: "composizione", t: "La musica spettrale: Partiels di Grisey, l'analisi dello spettro del trombone e la sintesi strumentale" },
  { c: "composizione", t: "La micropolifonia di Ligeti: Atmosphères, il canone sovrasaturo e la percezione della massa sonora" },
  { c: "composizione", t: "L'aleatorietà controllata di Lutosławski: le sezioni ad libitum dai Jeux vénitiens in poi" },
  { c: "composizione", t: "Citazione e collage: il terzo movimento della Sinfonia di Berio come commento a Mahler" },
  { c: "composizione", t: "La musica stocastica di Xenakis: Metastaseis, i glissandi di massa e il padiglione Philips" },
  { c: "composizione", t: "Il phasing di Steve Reich: da It's Gonna Rain a Piano Phase, processo graduale e pattern risultanti" },
  { c: "composizione", t: "La musique concrète di Pierre Schaeffer: objet sonore, ascolto ridotto e il solfège des objets" },
  { c: "composizione", t: "Lo studio di Colonia e la elektronische Musik: la sintesi additiva pura in Studie II di Stockhausen" },
  { c: "composizione", t: "L'accordo mistico di Skrjabin: armonia quartale, sintesi delle arti e il progetto Mysterium" },
  { c: "composizione", t: "Bartók e il sistema assiale di Ernő Lendvai: sezione aurea e Fibonacci — teoria o sovrainterpretazione?" },
  { c: "composizione", t: "Il linguaggio di Messiaen: modi a trasposizione limitata, ritmi non retrogradabili e accordi con risonanza" },
  { c: "composizione", t: "L'orchestrazione come disciplina: i trattati di Berlioz e Rimskij-Korsakov a confronto" },
  { c: "composizione", t: "Il tintinnabuli di Arvo Pärt: voce melodica e voce tintinnabulare, regole e ambiguità analitiche" },
  { c: "composizione", t: "Harry Partch e la just intonation estesa: la scala a 43 gradi e gli strumenti costruiti su misura" },
  { c: "composizione", t: "La microtonalità sistematica: i quarti di tono di Hába e l'ultracromatismo di Wyschnegradsky" },
  { c: "composizione", t: "La New Complexity: la notazione iper-dettagliata di Ferneyhough e il problema dell'ineseguibilità" },
  { c: "composizione", t: "La composizione algoritmica: dalla Illiac Suite di Hiller alla composizione assistita con OpenMusic" },
  { c: "composizione", t: "Il serialismo integrale: Structures Ia di Boulez, Mode de valeurs di Messiaen e l'organizzazione totale dei parametri" },

  // --------------------- GENERI E POPULAR MUSIC (25) ---------------------
  { c: "generi", t: "Il Delta blues: blue notes, forma AAB e il dibattito accademico sull'esistenza della 'scala blues'" },
  { c: "generi", t: "L'armonia del bebop: sostituzione di tritono, upper structures e il vocabolario di Parker e Powell" },
  { c: "generi", t: "Il modal jazz: Kind of Blue, i modi come campi armonici e l'abbandono della progressione funzionale" },
  { c: "generi", t: "Il free jazz e l'armolodia di Ornette Coleman: cosa significa davvero suonare 'senza accordi'" },
  { c: "generi", t: "La bossa nova: la batida di João Gilberto, la sincope brasiliana e il debito col samba de morro" },
  { c: "generi", t: "Il flamenco: i palos, il compás dodecuplo di soleá e bulería e la cadenza andalusa" },
  { c: "generi", t: "Il tango: dalla guardia vieja al nuevo tango di Piazzolla, tra habanera, milonga e fuga" },
  { c: "generi", t: "Il funk e 'The One': la concezione ritmica di James Brown e l'analisi del groove" },
  { c: "generi", t: "Le origini dell'hip-hop: il merry-go-round di Kool Herc, il breakbeat e la nascita del DJing" },
  { c: "generi", t: "Il sampling: l'Amen break, la sua diffusione e la giurisprudenza sul campionamento musicale" },
  { c: "generi", t: "Techno di Detroit e house di Chicago: genealogie, TR-808, TB-303 e il ruolo delle macchine 'fallite'" },
  { c: "generi", t: "Il dub giamaicano: King Tubby, lo studio di registrazione come strumento e la versione come pratica" },
  { c: "generi", t: "Il progressive rock: forme estese, metri irregolari e le appropriazioni della musica colta" },
  { c: "generi", t: "Il son cubano e la clave: struttura a due battute, direzionalità 3-2/2-3 e la derivazione della salsa" },
  { c: "generi", t: "Il fado: saudade, la guitarra portuguesa e la canonizzazione di Amália Rodrigues" },
  { c: "generi", t: "Dal gospel al soul: melisma, call and response e la secolarizzazione del sacro in Ray Charles e Aretha Franklin" },
  { c: "generi", t: "La scuola genovese dei cantautori: metrica, prosodia e il problema di cantare in italiano" },
  { c: "generi", t: "L'ambient di Brian Eno: Music for Airports, la musica generativa e l'ascolto ambientale" },
  { c: "generi", t: "Il krautrock e il motorik: Neu!, Can e la ritmica meccanica come estetica" },
  { c: "generi", t: "La disco: il four-on-the-floor, Giorgio Moroder e la produzione in studio come composizione" },
  { c: "generi", t: "Il punk e la sottocultura: l'analisi di Dick Hebdige e la retorica dell'autenticità DIY" },
  { c: "generi", t: "Il metal estremo: tecniche vocali gutturali, blast beat e la nascita dei metal studies accademici" },
  { c: "generi", t: "La musica per videogiochi: il chiptune, i vincoli tecnici del NES e la composizione adattiva" },
  { c: "generi", t: "Il bluegrass: lo stile Scruggs al banjo, l'high lonesome sound e la costruzione della tradizione" },
  { c: "generi", t: "Lo swing e le big band: section writing, arrangiamento e la composizione basata sul riff" },

  // -------------------------- ETNOMUSICOLOGIA (25) --------------------------
  { c: "etno", t: "Il gamelan giavanese: accordature slendro e pelog, irama e la struttura colotomica" },
  { c: "etno", t: "Il raga hindustani: that, rasa, gharana e l'architettura dell'alap" },
  { c: "etno", t: "Il tala: cicli ritmici hindustani e carnatici, il tihai e il solfeggio ritmico konnakol" },
  { c: "etno", t: "Il maqam arabo: gli ajnas, i quarti di tono e le convenzioni della modulazione modale" },
  { c: "etno", t: "Il radif persiano: dastgah, gushe e la trasmissione orale del repertorio classico iraniano" },
  { c: "etno", t: "Il canto difonico tuvano: khöömei, sygyt e kargyraa — produzione vocale e analisi spettrale" },
  { c: "etno", t: "La polifonia georgiana: il krimanchuli, le triadi non temperate e i sistemi di accordatura regionali" },
  { c: "etno", t: "Il canto a tenore sardo: la quintina, le formanti e il timbro gutturale di bassu e contra" },
  { c: "etno", t: "Le polifonie dei pigmei Aka: yodel, hoquetus e le registrazioni multitraccia di Simha Arom" },
  { c: "etno", t: "La mbira dzavadzimu degli Shona: cicli armonici, pattern interlocking e la cerimonia bira" },
  { c: "etno", t: "I tamburi parlanti dell'Africa occidentale: surrogati linguistici e la codifica dei toni" },
  { c: "etno", t: "Il gagaku giapponese: togaku e komagaku, lo sho e la questione del 'rallentamento' storico" },
  { c: "etno", t: "Il pansori coreano: timbro, tecnica vocale e i cinque racconti sopravvissuti del repertorio" },
  { c: "etno", t: "Il qawwali sufi: struttura, intensificazione estatica e la mediazione discografica di Nusrat Fateh Ali Khan" },
  { c: "etno", t: "La musica gnawa del Marocco: pentatonismo, guembri e i rituali di trance lila" },
  { c: "etno", t: "Lo joik sami: struttura circolare, referenzialità e la rivitalizzazione identitaria" },
  { c: "etno", t: "Il klezmer: i modi freygish e mi sheberakh, gli ornamenti krekhts e il revival americano" },
  { c: "etno", t: "Il canto bizantino: gli otto echoi, l'ison e la notazione neumatica della Nuova Metodo" },
  { c: "etno", t: "Lo shakuhachi e l'honkyoku: notazione katakana, il ma e l'estetica del suono singolo" },
  { c: "etno", t: "La bi-musicality di Mantle Hood: imparare a suonare come metodo di ricerca etnomusicologica" },
  { c: "etno", t: "La trascrizione in etnomusicologia: la dicotomia emic/etic e il melografo di Charles Seeger" },
  { c: "etno", t: "La scuola comparata di Berlino: Stumpf, Hornbostel e il Phonogramm-Archiv" },
  { c: "etno", t: "L'afrobeat di Fela Kuti: poliritmia, forme estese e la musica come pratica politica" },
  { c: "etno", t: "La cumbia: dalle origini afro-colombiane alle riappropriazioni transnazionali (chicha, sonidera, digitale)" },
  { c: "etno", t: "Le launeddas sarde: respirazione circolare, polifonia a bordone e le registrazioni di Bentzon" },

  // --------------------- ACUSTICA E PSICOACUSTICA (25) ---------------------
  { c: "acustica", t: "La serie armonica e il timbro: l'analisi di Fourier applicata ai suoni musicali" },
  { c: "acustica", t: "Temperamento equabile vs intonazione naturale: comma sintonico, comma pitagorico e i loro compromessi" },
  { c: "acustica", t: "Il temperamento mesotonico a quarto di comma: terze pure, quinta del lupo e i tasti spezzati" },
  { c: "acustica", t: "I temperamenti irregolari (Werckmeister, Kirnberger, Vallotti) e il dibattito sul 'buon temperamento' di Bach" },
  { c: "acustica", t: "La teoria della ruvidezza di Helmholtz: i battimenti come base fisica della dissonanza" },
  { c: "acustica", t: "Bande critiche e membrana basilare: la curva di Plomp e Levelt e la consonanza sensoriale" },
  { c: "acustica", t: "La fondamentale mancante: pitch virtuale e i modelli di percezione dell'altezza" },
  { c: "acustica", t: "Le curve isofoniche di Fletcher e Munson: loudness, phon e le conseguenze per il mixaggio" },
  { c: "acustica", t: "L'acustica delle sale da concerto: la formula di Sabine, il tempo di riverberazione e i parametri C80 e ITDG" },
  { c: "acustica", t: "La formante del cantante lirico: come una voce buca l'orchestra, spettro e vibrato" },
  { c: "acustica", t: "L'acustica delle canne d'organo: canne labiali e ad ancia, scaling e composizione dei registri" },
  { c: "acustica", t: "Gli archi e il moto di Helmholtz: stick-slip, pressione dell'arco e il punto di contatto" },
  { c: "acustica", t: "L'inarmonicità delle corde di pianoforte e lo stretching della curva di accordatura (curva di Railsback)" },
  { c: "acustica", t: "I modi di vibrazione delle membrane: perché il timpano ha un'altezza definita e il rullante no" },
  { c: "acustica", t: "Le figure di Chladni e i modi di vibrazione delle tavole armoniche del violino" },
  { c: "acustica", t: "L'effetto precedenza (Haas) e la localizzazione del suono: ITD, ILD e l'ascolto binaurale" },
  { c: "acustica", t: "L'orecchio assoluto: basi genetiche, periodo critico e la prevalenza nei parlanti di lingue tonali" },
  { c: "acustica", t: "La scala di Shepard e il glissando di Risset: i paradossi della percezione circolare dell'altezza" },
  { c: "acustica", t: "Il tritone paradox di Diana Deutsch e l'influenza della lingua madre sulla percezione" },
  { c: "acustica", t: "La sincronizzazione sensomotoria: beat induction, tapping e le basi neurali dell'entrainment ritmico" },
  { c: "acustica", t: "L'amusia congenita: cosa rivela sulla architettura cognitiva della percezione melodica" },
  { c: "acustica", t: "L'aspettativa musicale: la teoria ITPRA di David Huron e i modelli predittivi tipo IDyOM" },
  { c: "acustica", t: "Il frisson musicale: brividi, dopamina e i correlati fisiologici del piacere musicale" },
  { c: "acustica", t: "I profili tonali di Krumhansl e Kessler: la gerarchia tonale misurata empiricamente" },
  { c: "acustica", t: "La storia del diapason: dal La barocco al 440 Hz, le guerre del pitch e la normazione internazionale" },

  // ---------------- ORGANOLOGIA E PRASSI ESECUTIVA (25) ----------------
  { c: "organologia", t: "La classificazione Hornbostel-Sachs: logica, revisioni e i suoi limiti epistemologici" },
  { c: "organologia", t: "La liuteria cremonese: vernici, bombature e cosa dicono davvero dendrocronologia e analisi CT degli Stradivari" },
  { c: "organologia", t: "Clavicembalo e fortepiano: meccanica a salterello contro meccanica a martelletti, e le conseguenze sul repertorio" },
  { c: "organologia", t: "La viola da gamba: costruzione, accordatura per quarte e terza, e le ragioni del suo declino" },
  { c: "organologia", t: "Violino barocco e violino moderno: montatura, corde di budello, arco convesso e la trasformazione ottocentesca" },
  { c: "organologia", t: "Il corno naturale e la tecnica dei suoni chiusi: come si suonava cromatico senza pistoni" },
  { c: "organologia", t: "La tromba naturale e il registro clarino: la virtuosità barocca perduta e la sua riscoperta" },
  { c: "organologia", t: "Theobald Böhm e il flauto moderno: acustica, fori e la meccanica ad anelli" },
  { c: "organologia", t: "L'invenzione dei pistoni negli ottoni: cronologia, brevetti e le conseguenze sull'orchestrazione romantica" },
  { c: "organologia", t: "Serpentone, oficleide e la nascita della tuba: la voce grave degli ottoni prima e dopo il 1835" },
  { c: "organologia", t: "L'organo barocco nordtedesco: Arp Schnitger, il Werkprinzip e il repertorio di Buxtehude" },
  { c: "organologia", t: "Theremin e onde Martenot: i primi strumenti elettronici e il loro ingresso in orchestra" },
  { c: "organologia", t: "Il sintetizzatore modulare: Moog contro Buchla, east coast e west coast synthesis" },
  { c: "organologia", t: "Il pianoforte preparato di John Cage: tassonomia delle preparazioni e problemi di notazione" },
  { c: "organologia", t: "Il movimento della prassi storicamente informata: da Dolmetsch a Harnoncourt, strumenti originali e filologia del suono" },
  { c: "organologia", t: "L'ornamentazione barocca: trilli, appoggiature e le tavole di Bach, Couperin e Quantz a confronto" },
  { c: "organologia", t: "La cadenza nel concerto classico: improvvisazione, scrittura e le testimonianze su Mozart e Beethoven" },
  { c: "organologia", t: "Il diapason storico: variazioni regionali tra Sei e Ottocento e le conseguenze per l'esecuzione odierna" },
  { c: "organologia", t: "Le notes inégales: la convenzione francese dell'ineguaglianza e i suoi confini geografici" },
  { c: "organologia", t: "La realizzazione del basso continuo: trattatistica, stili nazionali e il ruolo del cembalista" },
  { c: "organologia", t: "Il castrato: fisiologia, repertorio, Farinelli e l'unica voce registrata (Alessandro Moreschi)" },
  { c: "organologia", t: "Il belcanto e la sua didattica: da Tosi e Mancini alla scuola di García e all'invenzione del laringoscopio" },
  { c: "organologia", t: "Il vibrato negli archi: da ornamento selettivo a suono di default — le prove nelle prime registrazioni" },
  { c: "organologia", t: "Il portamento vocale e strumentale: una prassi espressiva scomparsa documentata dai dischi acustici" },
  { c: "organologia", t: "La nascita del direttore d'orchestra moderno: da Berlioz a von Bülow, tra battuta, memoria e interpretazione" },

  // ------------------- NOTAZIONE E MUSICOLOGIA (25) -------------------
  { c: "musicologia", t: "I neumi: dalla notazione adiastematica in campo aperto al tetragramma guidoniano" },
  { c: "musicologia", t: "La semiologia gregoriana di Eugène Cardine: episema, liquescenza e i codici di San Gallo e Laon" },
  { c: "musicologia", t: "L'Ars cantus mensurabilis di Francone da Colonia: la notazione mensurale e il valore intrinseco delle figure" },
  { c: "musicologia", t: "La notazione mensurale bianca: legature, coloration e le trappole della trascrizione moderna" },
  { c: "musicologia", t: "Le intavolature per liuto: sistemi francese, italiano e tedesco a confronto" },
  { c: "musicologia", t: "Trascrivere la polifonia rinascimentale: stanghette, riduzione dei valori e le scelte che cambiano l'analisi" },
  { c: "musicologia", t: "La filologia musicale: stemma codicum, errori-guida e la critica del testo applicata ai manoscritti musicali" },
  { c: "musicologia", t: "Edizione critica vs Urtext: il mito del testo definitivo e il caso delle edizioni ottocentesche interventiste" },
  { c: "musicologia", t: "Gli abbozzi di Beethoven: le sketch studies e la genesi documentata della Sinfonia Eroica" },
  { c: "musicologia", t: "I cataloghi tematici: Köchel, BWV, Hoboken e i problemi di cronologia, autenticità e numerazione" },
  { c: "musicologia", t: "Falsi e attribuzioni dubbie: l'Adagio di Albinoni, i mottetti di Josquin e i metodi dell'attribuzionismo" },
  { c: "musicologia", t: "La New Musicology: Contemplating Music di Kerman e la critica al formalismo analitico" },
  { c: "musicologia", t: "Musicologia e studi di genere: le letture di Susan McClary e il dibattito sul canone" },
  { c: "musicologia", t: "Rockism e poptimism: la costruzione dell'autenticità nei popular music studies" },
  { c: "musicologia", t: "La topic theory: da Ratner a Monelle, i topoi del classicismo (caccia, militare, pastorale) e i loro limiti" },
  { c: "musicologia", t: "L'ermeneutica musicale di Lawrence Kramer: finestre ermeneutiche contro l'analisi formalista" },
  { c: "musicologia", t: "Text and Act di Richard Taruskin: l'autenticità del movimento early music come modernismo travestito" },
  { c: "musicologia", t: "L'archivistica sonora: cilindri di cera, 78 giri e le sfide della preservazione e digitalizzazione" },
  { c: "musicologia", t: "Il Music Information Retrieval: feature audio, corpus studies e i limiti dell'analisi computazionale della musica" },
  { c: "musicologia", t: "L'ecdotica dell'opera italiana: Philip Gossett e le edizioni critiche di Rossini e Verdi" },
  { c: "musicologia", t: "L'opera aperta di Umberto Eco e la musica indeterminata: Berio, Pousseur e la Terza Sonata di Boulez" },
  { c: "musicologia", t: "L'Affektenlehre barocca: la retorica musicale, le figure di Burmeister e il Der vollkommene Capellmeister di Mattheson" },
  { c: "musicologia", t: "Emotion and Meaning in Music di Leonard Meyer: aspettativa, inibizione e significato incorporato" },
  { c: "musicologia", t: "Adorno e la sociologia della musica: industria culturale, regressione dell'ascolto e la controversa critica al jazz" },
  { c: "musicologia", t: "R. Murray Schafer e l'ecologia acustica: soundscape, hi-fi e lo-fi, e il World Soundscape Project" },
];
